filter:
    excluded_paths:
        - tests/*
    dependency_paths:
        - vendor/

tools:
    external_code_coverage:
        timeout: 1200
        runs: 1

build:
    environment:
        php:
            version: "7.4"
